export const SET_CODE = "SET_CODE";
export const STORE_CODE = 'STORE_CODE';

export const STORE_PROJECT = 'STORE_PROJECT';
export const STORE_PROJECT_LIST = 'STORE_PROJECT_LIST';

export const STORE_ANALYSIS = 'STORE_ANALYSIS';
export const STORE_CURRENT_ANALYSIS = 'STORE_CURRENT_ANALYSIS';
export const STORE_CURRENT_ANALYSIS_KEY = 'STORE_CURRENT_ANALYSIS_KEY';
export const STORE_CURRENT_ANALYSIS_COMPLETION = 'STORE_CURRENT_ANALYSIS_COMPLETION';
export const START_ANALYSIS = 'START_ANALYSIS';
export const FINISH_ANALYSIS_SAST = 'FINISH_ANALYSIS_SAST';

export const STORE_INSTALLATION = 'STORE_INSTALLATION';
export const STORE_TOKEN = 'STORE_TOKEN';
export const FINISH_STORE_TOKEN = 'FINISH_STORE_TOKEN';


